// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace finalProject.Models;

public partial class APIContext : IdentityDbContext<ApplicationUser>
{
    public APIContext()
    {
    }

    public APIContext(DbContextOptions<APIContext> options)
        : base(options)
    {
    }

    public DbSet<Holiday> holidays { get; set; }
    public DbSet<Settings> settings { get; set; }
    public DbSet<Logs> logs { get; set; }
    public DbSet<NewEmployee> newEmployees { get; set; }
    public DbSet<Authorizations> authorizations { get; set; }
 

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-LVQUEUN\\SQLEXPRESS;Initial Catalog=api;Integrated Security=True");

    //protected override void OnModelCreating(ModelBuilder modelBuilder)
    //{
    //    OnModelCreatingPartial(modelBuilder);
    //}

    //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}