// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using finalProject.Models.Validations;
using Microsoft.EntityFrameworkCore;

namespace finalProject.Models
{
    [UniqueHoliday]
    public partial class Holiday
    {
        [Key]
        public int id { get; set; }

        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string name { get; set; }

        public DateOnly date { get; set; }
    }
}